USE FINAL
GO

-- TẠO BẢNG
DROP TABLE IF EXISTS LECTURER;
GO

CREATE TABLE LECTURER (
    ID			NVARCHAR(MAX),
	FACTORY		NVARCHAR(MAX),
	FIRSTNAME	NVARCHAR(MAX),
	LASTNAME	NVARCHAR(MAX),
	BIRTHDAY	NVARCHAR(MAX),
	GENDER		NVARCHAR(MAX),
    EMAIL		NVARCHAR(MAX),
	PHONE		NVARCHAR(MAX),
	[ADDRESS]	NVARCHAR(MAX),
	AVATAR		NVARCHAR(MAX),
    [PASSWORD]	NVARCHAR(MAX),
    ACTIVE BIT
);
GO

-- TẠO SEQUENCE
DROP SEQUENCE IF EXISTS LECTURER_SEQ;
GO
CREATE SEQUENCE LECTURER_SEQ
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    NO MAXVALUE
    CACHE 10;
GO

-- HÀM TẠO BẢNG TỪ CHUỖI
CREATE OR ALTER FUNCTION GETTABLE_LECTURER (@EMAIL NVARCHAR(MAX))
RETURNS TABLE
AS
RETURN
(
    SELECT * 
    FROM LECTURER LEC 
    WHERE LEC.EMAIL = @EMAIL
);
GO



-- HÀM KIỂM TRA INSERT
CREATE OR ALTER FUNCTION CHECK_INSERT_LECTURER(@EMAIL NVARCHAR(MAX))
RETURNS BIT
AS
BEGIN
    DECLARE @RESULT BIT = 0;
    IF NOT EXISTS (SELECT 1 FROM LECTURER WHERE EMAIL = @EMAIL)
        SET @RESULT = 1;
    RETURN @RESULT;
END;
GO

-- HÀM KIỂM TRA UPDATE
CREATE OR ALTER FUNCTION CHECK_UPDATE_LECTURER(@ID NVARCHAR(10))
RETURNS BIT
AS
BEGIN
    DECLARE @RESULT BIT = 1;
    --IF NOT EXISTS (SELECT 1 FROM LECTURER WHERE ID <> @ID)
    --    SET @RESULT = 1;
    RETURN @RESULT;
END;
GO

-- HÀM KIỂM TRA DELETE
CREATE OR ALTER FUNCTION CHECK_DELETE_LECTURER()
RETURNS BIT
AS
BEGIN
    RETURN 1;
END;
GO

-- HÀM INSERT
CREATE OR ALTER PROCEDURE INSERT_LECTURER 
	@FACTORY	NVARCHAR(MAX),
    @EMAIL		NVARCHAR(MAX),
	@FIRSTNAME	NVARCHAR(MAX),
	@LASTNAME	NVARCHAR(MAX),
	@BIRTHDAY	NVARCHAR(MAX),
	@GENDER		NVARCHAR(MAX),
	@PHONE		NVARCHAR(MAX),
	@ADDRESS	NVARCHAR(MAX),
	@AVATAR		NVARCHAR(MAX),
    @PASSWORD	NVARCHAR(MAX),
    @ACTIVE		BIT
AS
BEGIN
    IF DBO.CHECK_INSERT_LECTURER(@EMAIL) = 1
    BEGIN
        DECLARE @ID NVARCHAR(MAX);
        SET @ID = CONCAT('LEC', FORMAT(NEXT VALUE FOR LECTURER_SEQ, '00000000'));
        INSERT INTO LECTURER (
				ID
				,FACTORY 
				,EMAIL 
				,FIRSTNAME
				,LASTNAME
				,BIRTHDAY
				,GENDER
				,PHONE
				,[ADDRESS] 
				,AVATAR 
				,[PASSWORD]
				,ACTIVE )
        VALUES (
				@ID
				,@FACTORY 
				,@EMAIL 
				,@FIRSTNAME
				,@LASTNAME
				,@BIRTHDAY
				,@GENDER
				,@PHONE
				,@ADDRESS 
				,@AVATAR 
				,CONVERT(NVARCHAR(MAX), HASHBYTES('SHA2_512',@PASSWORD), 2)
				,@ACTIVE )
		SELECT 1 AS RESULT;
    END
    ELSE
    BEGIN
        THROW 50001, 'EMAIL OR MSSV ALREADY EXISTS', 1;
    END
END;
GO

-- HÀM UPDATE
CREATE OR ALTER PROCEDURE UPDATE_LECTURER 
    @ID			NVARCHAR(MAX),
	@FACTORY	NVARCHAR(MAX),
    @EMAIL		NVARCHAR(MAX),
	@FIRSTNAME	NVARCHAR(MAX),
	@LASTNAME	NVARCHAR(MAX),
	@BIRTHDAY	NVARCHAR(MAX),
	@GENDER		NVARCHAR(MAX),
	@PHONE		NVARCHAR(MAX),
	@ADDRESS	NVARCHAR(MAX),
	@AVATAR		NVARCHAR(MAX),
    @PASSWORD	NVARCHAR(MAX),
    @ACTIVE		BIT
AS
BEGIN
    IF DBO.CHECK_UPDATE_LECTURER(@ID) = 1
    BEGIN
        UPDATE LECTURER
        SET 
			FACTORY		= @FACTORY,
			EMAIL		= @EMAIL,
			FIRSTNAME	= @FIRSTNAME,
			LASTNAME	= @LASTNAME,
			BIRTHDAY	= @BIRTHDAY,
			GENDER		= @GENDER,
			PHONE		= @PHONE,
			[ADDRESS]	= @ADDRESS,
			AVATAR		= @AVATAR,
            [PASSWORD]	= CONVERT(NVARCHAR(MAX), HASHBYTES('SHA2_512',@PASSWORD), 2),
            ACTIVE = @ACTIVE
        WHERE ID = @ID;
    END
    ELSE
    BEGIN
        THROW 50002, 'EMAIL ALREADY EXISTS FOR ANOTHER USER', 1;
    END;
END;
GO

-- HÀM DELETE
CREATE OR ALTER PROCEDURE DELETE_LECTURER 
    @ID NVARCHAR(MAX)
AS
BEGIN
    IF DBO.CHECK_DELETE_LECTURER() = 1
    BEGIN
        DELETE FROM LECTURER WHERE ID = @ID;
    END
    ELSE
    BEGIN
        THROW 50003, 'DELETE OPERATION NOT ALLOWED', 1;
    END
END;
GO

CREATE OR ALTER PROCEDURE TRYLOGIN_LECTURER
    @EMAIL NVARCHAR(MAX),
    @PASSWORD NVARCHAR(MAX)
AS
BEGIN
    SET NOCOUNT ON;

	DECLARE @MYPASS NVARCHAR(MAX);

    SELECT @MYPASS = [PASSWORD]
    FROM LECTURER
    WHERE EMAIL = @EMAIL;

	IF CONVERT(NVARCHAR(MAX), HASHBYTES('SHA2_512', @PASSWORD), 2) = @MYPASS
	BEGIN
		SELECT 1 AS Result;
	END
	ELSE
	BEGIN
		THROW 50005, N'MẬT KHẨU KHÔNG ĐÚNG', 1;
	END
END;
GO


EXEC INSERT_LECTURER 
    @FACTORY = N'cntt', 
    @EMAIL = N'LECTURER1@example.com', 
    @FIRSTNAME = N'Nguyễn Văn', 
    @LASTNAME = N'A', 
    @BIRTHDAY = N'01/01/2000', 
    @GENDER = N'NAM', 
    @PHONE = N'111-111-1111', 
    @ADDRESS = N'123 Đường 1, Quận A, Thành phố X', 
    @AVATAR = N'avatar_url_1',
    @PASSWORD = N'pass123',
    @ACTIVE = 1;

EXEC INSERT_LECTURER 
    @FACTORY = N'httt', 
    @EMAIL = N'LECTURER2@example.com', 
    @FIRSTNAME = N'Trần', 
    @LASTNAME = N'Thị B', 
    @BIRTHDAY = N'15/05/1998', 
    @GENDER = N'NAM', 
    @PHONE = N'222-222-2222', 
    @ADDRESS = N'456 Đường 2, Quận B, Thành phố Y', 
    @AVATAR = N'avatar_url_2',
    @PASSWORD = N'pass234',
    @ACTIVE = 1;

EXEC INSERT_LECTURER 
    @FACTORY = N'ckm', 
    @EMAIL = N'LECTURER3@example.com', 
    @FIRSTNAME = N'Lê', 
    @LASTNAME = N'Hồng', 
    @BIRTHDAY = N'25/09/2001', 
    @GENDER = N'NAM', 
    @PHONE = N'333-333-3333', 
    @ADDRESS = N'789 Đường 3, Quận C, Thành phố Z', 
    @AVATAR = N'avatar_url_3',
    @PASSWORD = N'pass345',
    @ACTIVE = 0;

EXEC INSERT_LECTURER 
    @FACTORY = N'cnm', 
    @EMAIL = N'LECTURER4@example.com', 
    @FIRSTNAME = N'Phạm', 
    @LASTNAME = N'Thị D', 
    @BIRTHDAY = N'10/11/1999', 
    @GENDER = N'NAM', 
    @PHONE = N'444-444-4444', 
    @ADDRESS = N'101 Đường 4, Quận D, Thành phố W', 
    @AVATAR = N'avatar_url_4',
    @PASSWORD = N'pass456',
    @ACTIVE = 1;

EXEC INSERT_LECTURER 
    @FACTORY = N'CNTT', 
    @EMAIL = N'LECTURER5@example.com', 
    @FIRSTNAME = N'Hoàng', 
    @LASTNAME = N'Văn', 
    @BIRTHDAY = N'03/07/2002', 
    @GENDER = N'NAM', 
    @PHONE = N'555-555-5555', 
    @ADDRESS = N'111 Đường 5, Quận E, Thành phố V', 
    @AVATAR = N'avatar_url_5',
    @PASSWORD = N'pass567',
    @ACTIVE = 0;



SELECT * FROM GETTABLE_LECTURER(N'LECTURER5@example.com')
select * from LECTURER